/* Instruction shapes mined from real controller listings by
 * tools/build-shapes.js — DO NOT EDIT, re-run the tool instead.
 * 438 programs, 16479 instructions, 457 shapes. */
(function (global) {
  var dict = {
   "built": "2026-10-08",
   "programs": 438,
   "lines": 16479,
   "shapes": {
    "LBL[n]": [ 2700, "LBL[2]"],
    "JMP LBL[n]": [ 2084, "JMP LBL[1]"],
    "R[n]=N": [ 761, "R[8:Task-JMP LBL]=0"],
    "CALL PROG": [ 505, "CALL _GRIP_OPEN"],
    "DO[n]=OFF": [ 503, "DO[17:Conv Picked]=OFF"],
    "F[n]=(OFF)": [ 416, "F[1014:BGL-Custom Ack]=(OFF)"],
    "IF (DO[n]),JMP LBL[n]": [ 415, "IF (DO[33:At Home]),JMP LBL[200]"],
    "UFRAME_NUM=N": [ 386, "UFRAME_NUM=8"],
    "CALL PROG(N,N,N,N)": [ 365, "CALL _SET_OFFS(15,0,0,61)"],
    "DO[n]=ON": [ 365, "DO[17:Conv Picked]=ON"],
    "WAIT (DO[n])": [ 364, "WAIT (DO[201:At Conv Appr])"],
    "PR[n]=PR[n]": [ 312, "PR[99:*LPOS]=PR[98:*UTL-Set]"],
    "J PR[n] R[n]% CNTN": [ 308, "J PR[1:Home] R[202:Speed-J]% CNT50"],
    "CALL PROG(N)": [ 252, "CALL _TRANSIT(0)"],
    "L PR[n] R[n]mm/sec CNTN": [ 246, "L PR[22:ConvPk Wait] R[201:Speed-L]mm/sec CNT50"],
    "UTOOL_NUM=N": [ 241, "UTOOL_NUM=9"],
    "R[n]=R[n]": [ 230, "R[32:*DumpUTL-Offset]=R[83:*BoxHt-save]"],
    "ENDIF": [ 207, "ENDIF"],
    "IF (F[n]),JMP LBL[n]": [ 180, "IF (F[101:Sys Checks]),JMP LBL[999]"],
    "PAUSE": [ 168, "PAUSE"],
    "WAIT N(sec)": [ 167, "WAIT   1.00(sec)"],
    "J PR[n] R[n]% FINE": [ 160, "J PR[6:*Transit] R[211:RcvFast-J]% FINE"],
    "PR[n,n]=N": [ 143, "PR[91,3:*temp1]=0"],
    "=N,JMP LBL[n]": [ 130, "=20,JMP LBL[921]"],
    "F[n]=(ON)": [ 127, "F[1010:BGL Chk-Running]=(ON)"],
    "IF (DI[n]),JMP LBL[n]": [ 111, "IF (DI[17:Conv Pk Rdy]),JMP LBL[5]"],
    "L PR[n] R[n]mm/sec FINE": [ 111, "L PR[31:*Dump-Start] R[203:BoxSpd-L]mm/sec FINE"],
    "L PR[n] R[n]mm/sec CNTN Offset": [ 90, "L PR[35:*Dump-End] R[34:*ShakeSpd]mm/sec CNT10 Offset"],
    "IF (!DO[n]),JMP LBL[n]": [ 89, "IF (!DO[203:At Hopper Appr]),JMP LBL[100]"],
    "ELSE": [ 88, "ELSE"],
    "CALL PROG(N,'s','s')": [ 84, "CALL _SET_ALARM(2,'Status ID not 0 with no Box in ','Grip. Reset R[101] Sts ID to 0.')"],
    "IF (R[n]<N),R[n]=(N)": [ 81, "IF (R[93:*tempZ]<225),R[93:*tempZ]=(225)"],
    "J PR[n] N% CNTN": [ 80, "J PR[21:Conv Appr] 10% CNT100"],
    "IF (F[n]),CALL PROG": [ 78, "IF (F[101:Sys Checks]),CALL _SYS_CHECKS"],
    "IF (R[n]>N),R[n]=(N)": [ 77, "IF (R[31:*DumpSpd]>2000),R[31:*DumpSpd]=(500)"],
    "PR[n]=LPOS": [ 74, "PR[99:*LPOS]=LPOS"],
    "IF (R[n]<N OR R[n]>N),JMP LBL[n]": [ 70, "IF (R[42:*DropDist-Offs]<5 OR R[42:*DropDist-Offs]>315),JMP LBL[700]"],
    "IF R[n]=N,JMP LBL[n]": [ 67, "IF R[70:*Reject Sts]=0,JMP LBL[220]"],
    "IF (R[n]=N) THEN": [ 65, "IF (R[291:*Timeout-Set]=0) THEN"],
    "PR[n,n]=(-N)": [ 63, "PR[91,1:*temp1]=(-500)"],
    "L PR[n] R[n]mm/sec CNTN Tool_Offset": [ 57, "L PR[56:*PLpos-Meas] R[205:PalSpd-L]mm/sec CNT75 Tool_Offset"],
    "L PR[n] Nmm/sec CNTN Tool_Offset": [ 55, "L PR[20:Conv Pk] 300mm/sec CNT100 Tool_Offset"],
    "J PR[n] N% FINE": [ 53, "J PR[11] 100% FINE"],
    "WAIT (DI[n])": [ 53, "WAIT (DI[17:Conv Pk Rdy])"],
    "IF (!DI[n]),JMP LBL[n]": [ 51, "IF (!DI[1:Auto Mode]),JMP LBL[999]"],
    "IF R[n]>N,JMP LBL[n]": [ 49, "IF R[87:*Box/Pal Lg-save]>450,JMP LBL[452]"],
    "R[n]=(-N)": [ 47, "R[300:*Status]=(-1)"],
    "CALL PROG((-N),N,(-N),N)": [ 45, "CALL _SET_OFFS((-650),0,(-20),61)"],
    "R[n]=R[n]+N": [ 45, "R[470:WaitTmout-Def]=R[470:WaitTmout-Def]+1"],
    "CALL PROG((-N))": [ 44, "CALL _TRANSIT((-90))"],
    "J PR[n] N% CNTN Offset": [ 44, "J PR[30:*Hood Pk Pl] 75% CNT100 Offset"],
    "WAIT (!DI[n])": [ 42, "WAIT (!DI[17:Conv Pk Rdy])"],
    "IF (R[n]=N),JMP LBL[n]": [ 41, "IF (R[101:*EOAT-Box Sts]=10),JMP LBL[610]"],
    "PR[n,n]=R[n]": [ 41, "PR[91,3:*temp1]=R[93:*tempZ]"],
    "CALL PROG(N,(-N),N,N)": [ 39, "CALL _SET_OFFS(0,(-500),0,60)"],
    "R[n]=GI[n]": [ 39, "R[93:*tempZ]=GI[5:Box Ht]"],
    "IF (!F[n]),JMP LBL[n]": [ 37, "IF (!F[20:Conv Pk Rdy]),JMP LBL[100]"],
    "IF (DO[n] OR DO[n]),JMP LBL[n]": [ 36, "IF (DO[201:At Conv Appr] OR DO[202:At Conv Wait]),JMP LBL[999]"],
    "L PR[n] Nmm/sec FINE Offset": [ 35, "L PR[43:Stack PK] 500mm/sec FINE Offset"],
    "IF (F[n]) THEN": [ 33, "IF (F[1010:BGL Chk-Running]) THEN"],
    "CALL PROG(R[n])": [ 32, "CALL _SET_WAIT(R[43:*WaitTm x100])"],
    "CALL PROG(N,N,(-N),N)": [ 31, "CALL _SET_OFFS(0,0,(-650),61)"],
    "L PR[n] Nmm/sec FINE Tool_Offset": [ 31, "L PR[20:Conv Pk] 700mm/sec FINE Tool_Offset"],
    "PR[n]=JPOS": [ 30, "PR[100:*JPOS]=JPOS"],
    "SELECT R[n]=N,JMP LBL[n]": [ 30, "SELECT R[101:*EOAT-Box Sts]=10,JMP LBL[921]"],
    "SR[n]=SR[n]": [ 30, "SR[1]=SR[11]"],
    "$sysvar$sysvar=N": [ 29, "$SSR.$STEPSTMTTYP=1"],
    "IF (R[n]=N),CALL PROG": [ 29, "IF (R[2:Manual TaskID]=10),CALL _RECOVER"],
    "CALL PROG(N,N,R[n],N)": [ 26, "CALL _SET_OFFS(0,0,R[83:*BoxHt-save],60)"],
    "IF (DI[n] AND !DI[n]),JMP LBL[n]": [ 26, "IF (DI[23:Inspect-Pass] AND !DI[24:Inspect-Fail]),JMP LBL[440]"],
    "L PR[n] Nmm/sec CNTN Offset": [ 26, "L PR[20:*Box Pk] 500mm/sec CNT50 Offset"],
    "R[n]=R[n]+R[n]": [ 26, "R[47:*EdgeFindStart]=R[57:*Edge-StartOffs]+R[94:*temp]"],
    "WAIT (DI[n]) TIMEOUT,LBL[n]": [ 26, "WAIT (DI[32:EOAT Clamped]) TIMEOUT,LBL[702]"],
    "DO[R[n]]=OFF": [ 25, "DO[R[99]]=OFF"],
    "IF R[n]<(-N),JMP LBL[n]": [ 25, "IF R[81:*X pos-Save]<(-25),JMP LBL[701]"],
    "DO[n]=PULSE,Nsec": [ 24, "DO[20:Dump Done]=PULSE,0.5sec"],
    "J PR[n] R[n]% CNTN Tool_Offset": [ 24, "J PR[21:Zone1Pallet] R[31:Speed-J]% CNT100 Tool_Offset"],
    "PR[n,n]=PR[n,n]+R[n]": [ 24, "PR[99,1:*LPOS]=PR[98,1:*UTL-Set]+R[93:*tempZ]"],
    "L PR[n] Nmm/sec CNTN Offset RT_LDN": [ 22, "L PR[43:Stack PK] 500mm/sec CNT50 Offset RT_LD175"],
    "CALL PROG((-N),N,N,N)": [ 21, "CALL _SET_OFFS((-675),0,40,61)"],
    "DO[R[n]]=ON": [ 21, "DO[R[491]]=ON"],
    "PR[n,n]=PR[n,n]": [ 21, "PR[6,1:*Transit]=PR[100,1:*JPOS]"],
    "R[n]=(N*R[n]+N*R[n]+N)": [ 21, "R[20:Hood Label]=(10*R[25:Curr Hood Zone]+5*R[26:Curr Hood Pal]+5)"],
    "R[n]=AR[n]": [ 21, "R[284:SR-NumAlarms]=AR[1]"],
    "CALL PROG(N,R[n],R[n],N)": [ 20, "CALL _SET_OFFS(0,R[44:Pallet PK Y],R[98:temp 2],60)"],
    "IF (R[n]=N OR R[n]=N),JMP LBL[n]": [ 20, "IF (R[101:*EOAT-Box Sts]=10 OR R[101:*EOAT-Box Sts]=20),JMP LBL[200]"],
    "PR[n]=PR[R[n]]": [ 20, "PR[70:*Cal Pos]=PR[R[77]]"],
    "R[n]=PR[n,n]": [ 19, "R[94:*temp4]=PR[99,4:*LPOS]"],
    "WAIT (!DO[n])": [ 19, "WAIT (!DO[63:BGLogic Off])"],
    "CALL PROG(R[n],R[n],R[n],N)": [ 18, "CALL _SET_OFFS(R[27:*Pk Rrtrt-Xoffs],R[28:*Pk Rtrt-Yoffs],R[29:*Pk Rtrt-Zoffs],60)"],
    "IF (R[n]=N),R[n]=(N)": [ 18, "IF (R[101:EOAT-Part Sts]=25),R[101:EOAT-Part Sts]=(20)"],
    "J PR[n] R[n]% CNTN Offset": [ 18, "J PR[22:ConvPk Wait] R[201:Speed-L]% CNT50 Offset"],
    "L PR[n] Nmm/sec FINE Offset Skip,LBL[n]": [ 18, "L PR[20:*Box Pk] 150mm/sec FINE Offset Skip,LBL[307]"],
    "L PR[n] R[n]mm/sec CNTN AP_LDN": [ 18, "L PR[21:Zone1Pallet] R[32:BoxSpd-L]mm/sec CNT0 AP_LD100"],
    "L PR[n] R[n]mm/sec FINE Offset": [ 18, "L PR[50:Trash PL] R[203:BoxSpd-L]mm/sec FINE Offset"],
    "L PR[n] R[n]mm/sec FINE Tool_Offset": [ 18, "L PR[70:Reject PL] R[203:BoxSpd-L]mm/sec FINE Tool_Offset"],
    "R[n]=R[n]-R[n]": [ 18, "R[96:*temp]=R[53:*Meas-HtOffs]-R[93:*temp-Z]"],
    "WAIT (!DI[n] AND !DI[n])": [ 18, "WAIT (!DI[23:Inspect-Pass] AND !DI[24:Inspect-Fail])"],
    "IF (R[n]<(-N)),R[n]=((-N))": [ 17, "IF (R[27:*Pk Rrtrt-Xoffs]<(-200)),R[27:*Pk Rrtrt-Xoffs]=((-100))"],
    "IF (R[n]<N),JMP LBL[n]": [ 17, "IF (R[81:*BoxLg-save]<50),JMP LBL[701]"],
    "R[n]=(N*R[n]+R[n]+N)": [ 17, "R[21:Hood Position]=(2*R[25:Curr Hood Zone]+R[26:Curr Hood Pal]+35)"],
    "WAIT (DO[n] OR DO[n])": [ 17, "WAIT (DO[203:At VacTL Nest Appr] OR DO[204:At PalTL Nest Appr])"],
    "CALL PROG(N,(-N),(-N),N)": [ 16, "CALL _SET_OFFS(0,(-475),(-15),60)"],
    "F[n]=($sysvar$sysvar)": [ 16, "F[501:DCS-At Conv]=($DCSS_PSTAT.$STATUS_CPC[11])"],
    "IF ((R[n]=N OR R[n]=N) AND DO[n]),JMP LBL[n]": [ 16, "IF ((R[25:*Slot-Colmn]=1 OR R[25:*Slot-Colmn]=2) AND DO[211:ON :At L-RacksApr]),JMP LBL[210]"],
    "IF (R[n]=N OR R[n]=N OR R[n]=N OR R[n]=N),JMP LBL[n]": [ 16, "IF (R[100:JMP to LBL]=60 OR R[100:JMP to LBL]=70 OR R[100:JMP to LBL]=71 OR R[100:JMP to LBL]=72),JMP LBL[350]"],
    "L PR[n] Nmm/sec CNTN": [ 16, "L PR[22:ConvPk Wait] 300mm/sec CNT100"],
    "L PR[R[n]] Nmm/sec FINE Offset": [ 16, "L PR[R[20]] 1500mm/sec FINE Offset"],
    "PR[n,n]=((-N))": [ 16, "PR[61,4:Tool Offs]=((-3.5))"],
    "IF (!DI[n] OR !DI[n]),JMP LBL[n]": [ 15, "IF (!DI[1:Auto Mode] OR !DI[2:Start]),JMP LBL[999]"],
    "IF (F[n] AND F[n]) THEN": [ 15, "IF (F[1011:BGL-Custom Chk] AND F[1014:BGL-Custom Ack]) THEN"],
    "IF DI[n]=OFF,JMP LBL[n]": [ 15, "IF DI[3:Pause]=OFF,JMP LBL[198]"],
    "L PR[n] Nmm/sec CNTN AP_LDN": [ 15, "L PR[21:Zone1Pallet] 750mm/sec CNT0 AP_LD100"],
    "PR[R[n],N]=AR[n]": [ 15, "PR[R[99],1]=AR[1]"],
    "PR[R[n],N]=N": [ 15, "PR[R[99],4]=0"],
    "R[n]=PR[n,n]-N": [ 15, "R[91:*tempX]=PR[70,1:Reject PL]-200"],
    "WAIT (DI[n] OR DI[n])": [ 15, "WAIT (DI[23:Inspect-Pass] OR DI[24:Inspect-Fail])"],
    "COL GUARD ADJUST N": [ 14, "COL GUARD ADJUST 100"],
    "DO[n] Alarm]=ON": [ 14, "DO[49:SR[1] Alarm]=ON"],
    "DO[n]=(OFF)": [ 14, "DO[39:At Hopper]=(OFF)"],
    "IF (R[n]<>N),JMP LBL[n]": [ 14, "IF (R[101:*EOAT-Box Sts]<>0),JMP LBL[701]"],
    "L P[n] Nmm/sec FINE": [ 14, "L P[2] 100mm/sec FINE"],
    "R[n]=GI[n]+N": [ 14, "R[99:*temp]=GI[2:ClampPos-act]+4"],
    "R[n]=R[n]*(-N)": [ 14, "R[72:*Cal-Y pos]=R[72:*Cal-Y pos]*(-1)"],
    "WAIT (F[n])": [ 14, "WAIT (F[221:At L-Ln Pk Appr])"],
    "$sysvar=N": [ 13, "$RGSPD_PREXE=1"],
    "IF (!F[n]) THEN": [ 13, "IF (!F[1017:BGL-Custom ON]) THEN"],
    "L PR[R[n]] Nmm/sec CNTN": [ 13, "L PR[R[20]] 1500mm/sec CNT50"],
    "PR[n,n]=PR[n,n]+N": [ 13, "PR[91,3:*temp1]=PR[99,3:*LPOS]+100"],
    "DO[n] Alarm]=OFF": [ 12, "DO[49:SR[1] Alarm]=OFF"],
    "IF (!DO[n]),CALL PROG": [ 12, "IF (!DO[32:OFF:EOAT Grab Pallet]),CALL _GRIP_PALLET"],
    "IF (R[n]>(-N)),R[n]=((-N))": [ 12, "IF (R[27:*Pk Rrtrt-Xoffs]>(-2)),R[27:*Pk Rrtrt-Xoffs]=((-2))"],
    "IF (R[n]>(R[n]-N)),JMP LBL[n]": [ 12, "IF (R[88:*Box/Pal Wd-Save]>(R[402:VacTL-Wd]-40)),JMP LBL[512]"],
    "IF (R[n]>=N),DO[n]=(ON)": [ 12, "IF (R[81:*BoxLg-save]>=200),DO[67:Vac-2 On]=(ON)"],
    "J PR[n] N% CNTN Tool_Offset": [ 12, "J PR[20:Conv Pk] 50% CNT100 Tool_Offset"],
    "J PR[n] N% FINE Offset": [ 12, "J PR[41:Stack-Meas-Orig] 100% FINE Offset"],
    "L PR[n] R[n]mm/sec CNTN Tool_Offset RT_LDN": [ 12, "L PR[21:Zone1Pallet] R[32:BoxSpd-L]mm/sec CNT100 Tool_Offset RT_LD100"],
    "R[n]=(PR[n,n]-R[n]-N)": [ 12, "R[43:Pallet PK Z]=(PR[42,3:Pal Z LPOS]-R[42:Pallet Distance]-110)"],
    "R[n]=PR[n,n]+N": [ 12, "R[93:*tempZ]=PR[20,3:Conv Pk]+125"],
    "R[n]=PR[n,n]+N+N": [ 12, "R[44:Pallet PK Y]=PR[98,2:LPOS]+100+351"],
    "R[n]=PR[R[n],N]": [ 12, "R[88]=PR[R[80],1]"],
    "SKIP CONDITION GI[n]<=N AND GI[n]>N": [ 12, "SKIP CONDITION GI[7:65245:EOAT Height Sens]<=220 AND GI[7:65245:EOAT Height Sens]>0"],
    "SKIP CONDITION GI[n]<=N OR GI[n]>=N": [ 12, "SKIP CONDITION GI[7:65245:EOAT Height Sens]<=0 OR GI[7:65245:EOAT Height Sens]>=400"],
    "SKIP CONDITION GI[n]>=R[n]": [ 12, "SKIP CONDITION GI[7:65245:EOAT Height Sens]>=R[42:Pallet Distance]"],
    "IF (F[n]),F[n]=(ON)": [ 11, "IF (F[1011:BGL-Custom Chk]),F[1014:BGL-Custom Ack]=(ON)"],
    "IF (GI[n]>(R[n]+N)),JMP LBL[n]": [ 11, "IF (GI[5:Pal Clamp Wd]>(R[476:AR-GrpClsWd]+80)),JMP LBL[702]"],
    "DO[n]=($sysvar$sysvar)": [ 10, "DO[60:Robot Jogged]=($MOR_GRP[1].$JOGGED)"],
    "IF (R[n]>N),JMP LBL[n]": [ 10, "IF (R[93:*tempZ]>600),JMP LBL[404]"],
    "IF (R[n]>R[n]),JMP LBL[n]": [ 10, "IF (R[81:*BoxLg-save]>R[280:Gripper Lg]),JMP LBL[151]"],
    "L PR[n] Nmm/sec FINE Skip,LBL[n]": [ 10, "L PR[31:*ScanPos1] 1500mm/sec FINE Skip,LBL[330]"],
    "MESSAGE[STACK NOT FOUND]": [ 10, "MESSAGE[STACK NOT FOUND]"],
    "PAYLOAD[n]": [ 10, "PAYLOAD[2:Vac Tool]"],
    "R[n]=R[n] DIV N": [ 10, "R[31:*DumpSpd]=R[31:*DumpSpd] DIV 1"],
    "UFRAME_NUM=R[n]": [ 10, "UFRAME_NUM=R[20:*RackNum]"],
    "UTOOL[n]=PR[n]": [ 10, "UTOOL[9:*HopDump]=PR[99:*LPOS]"],
    "WAIT (!DI[n] AND !DI[n]) TIMEOUT,LBL[n]": [ 10, "WAIT (!DI[23:Inspect-Pass] AND !DI[24:Inspect-Fail]) TIMEOUT,LBL[407]"],
    "WAIT (!DI[n]) TIMEOUT,LBL[n]": [ 10, "WAIT (!DI[31:EOAT Clamp Dn]) TIMEOUT,LBL[701]"],
    "DO[n]=(F[n])": [ 9, "DO[40:At Reject]=(F[503:DCS-At Reject])"],
    "GO[n]=N": [ 9, "GO[2:ClampPos-cmd]=0"],
    "IF (PR[n,n]<R[n]) THEN": [ 9, "IF (PR[99,3:*LPOS]<R[93:*tempZ]) THEN"],
    "L PR[n] Nmm/sec FINE": [ 9, "L PR[70:*Cal Pos] 1000mm/sec FINE"],
    "L PR[n] Nmm/sec FINE Offset Skip,LBL[n],PR[n]=LPOS": [ 9, "L PR[42:Pal Z LPOS] 50mm/sec FINE Offset Skip,LBL[710],PR[42:Pal Z LPOS]=LPOS"],
    "R[n]=R[n]/N": [ 9, "R[91:*temp-X]=R[87:*Box/Pal Lg-save]/2"],
    "$sysvar=R[n]": [ 8, "$WAITTMOUT=R[290:Timeout-Def]"],
    "CALL PROG(AR[n],AR[n])": [ 8, "CALL ACSET(AR[1],AR[2])"],
    "GO[n]=(N)": [ 8, "GO[2:ClampPos-cmd]=(0)"],
    "GO[n]=R[n]": [ 8, "GO[2:ClampPos-cmd]=R[99:*temp]"],
    "IF (!DO[n] AND !DO[n]),JMP LBL[n]": [ 8, "IF (!DO[33:At Home] AND !DO[37:At Transit]),JMP LBL[100]"],
    "IF (DI[n] AND DI[n]),JMP LBL[n]": [ 8, "IF (DI[65:OFF:Z1P1 Presence] AND DI[67:OFF:Z2P1 Presence]),JMP LBL[800]"],
    "IF (R[n]<(R[n]*(-N))),JMP LBL[n]": [ 8, "IF (R[96:*temp]<(R[425:StaticMeas-Tolr]*(-1))),JMP LBL[231]"],
    "IF (R[n]>N AND R[n]<N),R[n]=(N)": [ 8, "IF (R[11:Tst-SlotInRack]>9 AND R[11:Tst-SlotInRack]<15),R[11:Tst-SlotInRack]=(15)"],
    "IF R[n]<=N,JMP LBL[n]": [ 8, "IF R[83:*Z pos-Save]<=500,JMP LBL[260]"],
    "PR[n]=UTOOL[n]": [ 8, "PR[98:*UTL-Set]=UTOOL[1:BoxGrip]"],
    "R[n]=GI[n]-R[n]": [ 8, "R[93:*temp-Z]=GI[6:Vac/PalMeas-1]-R[421:Lsr2UTL Dist]"],
    "WAIT (DI[n] OR DI[n]) TIMEOUT,LBL[n]": [ 8, "WAIT (DI[30:EOAT Clamp Rdy] OR DI[32:EOAT Clamped]) TIMEOUT,LBL[701]"],
    "ENDFOR": [ 7, "ENDFOR"],
    "FOR R[n]=N TO N": [ 7, "FOR R[92:*tempY]=1 TO 5"],
    "IF (DI[n] AND R[n]=N),JMP LBL[n]": [ 7, "IF (DI[71:TL Chg Locked] AND R[5:Tool ID]=1),JMP LBL[110]"],
    "IF (DI[n] OR !DI[n]),JMP LBL[n]": [ 7, "IF (DI[65:OFF:Z1P1 Presence] OR !DI[66:OFF:Z1P2 Presence]),JMP LBL[999]"],
    "IF (F[n]),JMP LBL[R[n]]": [ 7, "IF (F[8:Task Rdy]),JMP LBL[R[8]]"],
    "IF (PR[n,n]<R[n]),JMP LBL[n]": [ 7, "IF (PR[99,1:*LPOS]<R[91:*tempX]),JMP LBL[430]"],
    "IF (R[n]<>N AND R[n]<>N AND R[n]<>N),JMP LBL[n]": [ 7, "IF (R[11:*PL-Tool ID]<>1 AND R[11:*PL-Tool ID]<>2 AND R[11:*PL-Tool ID]<>9),JMP LBL[700]"],
    "IF (R[n]<>N AND R[n]<>N),JMP LBL[n]": [ 7, "IF (R[12:*Appr-AR]<>1 AND R[12:*Appr-AR]<>2),JMP LBL[999]"],
    "IF (R[n]=N OR R[n]=N OR R[n]=N),JMP LBL[n]": [ 7, "IF (R[24:*Pk Appr Type]=1 OR R[24:*Pk Appr Type]=2 OR R[24:*Pk Appr Type]=4),JMP LBL[211]"],
    "IF R[n]<>N,JMP LBL[n]": [ 7, "IF R[428:EdgeFind-enbl]<>0,JMP LBL[210]"],
    "J PR[R[n]] N% CNTN Offset": [ 7, "J PR[R[20]] 75% CNT100 Offset"],
    "L PR[n] Nmm/sec FINE AP_LDN": [ 7, "L PR[21:Zone1Pallet] 500mm/sec FINE AP_LD200"],
    "L PR[R[n]] R[n]mm/sec FINE Offset": [ 7, "L PR[R[20]] R[32:BoxSpd-L]mm/sec FINE Offset"],
    "R[n]=R[n]*N": [ 7, "R[43:*WaitTm x100]=R[42:*CamDn-WaitTm]*100"],
    "CALL PROG(N,'s')": [ 6, "CALL _SET_ALARM(1,'EOAT Grip did not clamp.')"],
    "CALL PROG(N,N,N)": [ 6, "CALL A_ZONE_CHECK(80,81,85)"],
    "DO[n]=(F[n] OR F[n])": [ 6, "DO[38:At Conv]=(F[501:DCS-At Conv] OR F[21:At Conv-Ovrd])"],
    "DO[n]=(ON)": [ 6, "DO[41:At Trash]=(ON)"],
    "F[n]=(DI[n] OR DI[n])": [ 6, "F[101:Sys Checks]=(DI[3:Pause] OR DI[4:Request To Enter])"],
    "IF (AR[n]=N),JMP LBL[n]": [ 6, "IF (AR[1]=1),JMP LBL[110]"],
    "IF (PR[n,n]>R[n]) THEN": [ 6, "IF (PR[99,3:*LPOS]>R[93:*tempZ]) THEN"],
    "IF (R[n]<=N) THEN": [ 6, "IF (R[25:*Slot-Colmn]<=2) THEN"],
    "IF (R[n]>(-N) AND R[n]<N),JMP LBL[n]": [ 6, "IF (R[99:*temp]>(-40) AND R[99:*temp]<40),JMP LBL[200]"],
    "IF (R[n]>=N AND R[n]<=N),JMP LBL[n]": [ 6, "IF (R[80:*PalType-Save]>=1 AND R[80:*PalType-Save]<=4),JMP LBL[110]"],
    "J P[n] R[n]% CNTN DB Nmm,DO[n]=OFF": [ 6, "J P[6:Tansit PK] R[31:Speed-J]% CNT75 DB   10.0mm,DO[38:OFF:At Zone1P1]=OFF"],
    "J PR[n] N% CNTN DB Nmm,DO[n]=OFF": [ 6, "J PR[19:Zone1 Appr] 75% CNT100 DB   10.0mm,DO[39:OFF:At Zone1P2]=OFF"],
    "J PR[n] N% FINE Tool_Offset": [ 6, "J PR[20:Zone1P1-Orig ?] 75% FINE Tool_Offset"],
    "J PR[n] R[n]% CNTN DB Nmm,DO[n]=OFF": [ 6, "J PR[19:Zone1 Appr] R[31:Speed-J]% CNT100 DB   10.0mm,DO[39:OFF:At Zone1P2]=OFF"],
    "PR[n,n]=AR[n]": [ 6, "PR[6,1:*Transit]=AR[1]"],
    "PR[R[n]]=PR[n]": [ 6, "PR[R[20]]=PR[32:*Hook Pk]"],
    "R[n]=(((R[n]-N) DIV N)+N)": [ 6, "R[25:*Slot-Colmn]=(((R[11:Tst-SlotInRack]-1) DIV 7)+1)"],
    "R[n]=(((R[n]-N) MOD N)+N)": [ 6, "R[26:*Slot-Row]=(((R[11:Tst-SlotInRack]-1) MOD 7)+1)"],
    "R[n]=((R[n]-N)*R[n])": [ 6, "R[22:*X-Offs]=((R[25:*Slot-Colmn]-1)*R[381:Rack-Colmn Offs])"],
    "R[R[n]]=N": [ 6, "R[R[199]]=0"],
    "WAIT (!DI[R[n]])": [ 6, "WAIT (!DI[R[491]])"],
    "GO[n]=(R[n])": [ 5, "GO[1:Robot TaskID]=(R[2:Manual TaskID])"],
    "IF (!DI[n]),CALL PROG": [ 5, "IF (!DI[1:Auto Mode]),CALL __MANUAL"],
    "IF (!F[n]),$sysvar$sysvar=(N)": [ 5, "IF (!F[1024:Pwr Cycled ons]),$JCR_GRP[1].$JOG_COORD=(2)"],
    "IF (!F[n]),DO[n]=(ON)": [ 5, "IF (!F[1024:Pwr Cycled ons]),DO[112:Power Cycled]=(ON)"],
    "IF ((DI[n] AND GI[n]>N) OR DI[n]),JMP LBL[n]": [ 5, "IF ((DI[5:Run Task] AND GI[1:Task ID]>0) OR DI[4:Request To Enter]),JMP LBL[150]"],
    "IF ((UO[n] AND !UO[n]) OR DO[n]),DO[n]=(OFF)": [ 5, "IF ((UO[10:Busy] AND !UO[4:Prg paused]) OR DO[64:TP Prompt]),DO[113:Start]=(OFF)"],
    "IF ($sysvar$sysvar=N AND !F[n]) THEN": [ 5, "IF ($MOR_GRP[1].$JOGGED=1 AND !F[1022:Jogged ons]) THEN"],
    "IF ($sysvar$sysvar=N),DO[n]=(OFF)": [ 5, "IF ($MOR_GRP[1].$JOGGED=0),DO[60:Robot Jogged]=(OFF)"],
    "IF (DI[n] OR DI[n]),JMP LBL[n]": [ 5, "IF (DI[65:Vac-1 OK] OR DI[67:Vac-2 OK]),JMP LBL[730]"],
    "IF (DI[n]),CALL PROG": [ 5, "IF (DI[1:Auto Mode]),CALL __AUTO"],
    "IF (DO[n] OR F[n]) THEN": [ 5, "IF (DO[63:BGLogic Off] OR F[1010:BGL Chk-Running]) THEN"],
    "IF (PR[n,n]>N) THEN": [ 5, "IF (PR[99,1:*LPOS]>20) THEN"],
    "IF (R[n]=N OR DI[n]),CALL PROG": [ 5, "IF (R[2:Manual TaskID]=30 OR DI[4:Request To Enter]),CALL _SAFE"],
    "IF (R[n]>N) THEN": [ 5, "IF (R[11:Tst-SlotInRack]>26) THEN"],
    "IF DI[n]=ON,JMP LBL[n]": [ 5, "IF DI[1:Auto Mode]=ON,JMP LBL[998]"],
    "J PR[R[n]] R[n]% CNTN Tool_Offset": [ 5, "J PR[R[20]] R[31:Speed-J]% CNT100 Tool_Offset"],
    "L PR[n] Nmm/sec CNTN RT_LDN Offset": [ 5, "L PR[31:Hood Z1P1 Sm] 750mm/sec CNT100 RT_LD100 Offset"],
    "L PR[n] Nmm/sec FINE Tool_Offset AP_LDN": [ 5, "L PR[20:Conv Pk] 500mm/sec FINE Tool_Offset AP_LD640"],
    "L PR[n] R[n]mm/sec CNTN Offset RT_LDN": [ 5, "L PR[21:Zone1Pallet] R[30:Speed-L]mm/sec CNT100 Offset RT_LD75"],
    "OFFSET CONDITION PR[n]": [ 5, "OFFSET CONDITION PR[60:Frame Offs]"],
    "PR[n,n]=PR[n,n]-N": [ 5, "PR[91,2:*temp1]=PR[99,2:*LPOS]-15"],
    "R[n]=(DI[n])": [ 5, "R[371:*Outfd1 PL Rdy]=(DI[19:OFF:Outfd PL Rdy])"],
    "TOOL_OFFSET CONDITION PR[n]": [ 5, "TOOL_OFFSET CONDITION PR[61:Tool Offs]"],
    "WAIT (DI[n] AND DI[n]) TIMEOUT,LBL[n]": [ 5, "WAIT (DI[65:Vac-1 Ok] AND DI[68:Vac-4 Ok]) TIMEOUT,LBL[710]"],
    "WAIT DI[n]=OFF": [ 5, "WAIT DI[5:Run Task]=OFF"],
    "CALL PROG(R[n],N,(-N),N)": [ 4, "CALL _SET_OFFS(R[71:*Rjct PL Offs],0,(-15),61)"],
    "DO[n]=(!DO[n])": [ 4, "DO[65:OFF:Ext Clamp-Up]=(!DO[65:OFF:Ext Clamp-Up])"],
    "F[n]=(F[n] OR !DI[n])": [ 4, "F[10:ON :Condition Fault]=(F[1:ON :Part On Grip] OR !DI[69:OFF:Stack Presence])"],
    "IF (!DI[R[n]]),JMP LBL[n]": [ 4, "IF (!DI[R[492]]),JMP LBL[999]"],
    "IF (!DO[n] AND !DO[n] AND !DO[n] AND !DO[n]),JMP LBL[n]": [ 4, "IF (!DO[231:At Lapr-SmX/MdZ/R180] AND !DO[232:At Lapr-LgX/MdZ/R180] AND !DO[233:At Lapr-SmX/MdZ/R90] AND !DO[234:At Lapr-LgX/MdZ/R-90]),JMP LBL[999]"],
    "IF (!DO[n] AND !DO[n] AND !DO[n]),JMP LBL[n]": [ 4, "IF (!DO[251:At L-Rtrt-MedZ/R180] AND !DO[252:At L-Rtrt-MedZ/R90] AND !DO[253:At L-Rtrt-MedZ/R-90]),JMP LBL[999]"],
    "IF ((R[n]=N OR R[n]=N) AND R[n]>=N),JMP LBL[n]": [ 4, "IF ((R[101:EOAT-Part Sts]=25 OR R[101:EOAT-Part Sts]=65) AND R[32:*Pre-Zoffs Found]>=50),JMP LBL[150]"],
    "IF ((R[n]>(R[n]+N)) AND R[n]<>N),JMP LBL[n]": [ 4, "IF ((R[91:*temp-X]>(R[61:*PalOut-Stk Lg]+50)) AND R[60:*PalOut-Prev ID]<>0),JMP LBL[140]"],
    "IF ((R[n]>=N AND R[n]<=N) OR R[n]=N OR R[n]=N),JMP LBL[n]": [ 4, "IF ((R[5]>=1 AND R[5]<=168) OR R[5]=200 OR R[5]=201),JMP LBL[310]"],
    "IF (DI[n] OR R[n]<>N),JMP LBL[n]": [ 4, "IF (DI[1:Auto Mode] OR R[2:Manual TaskID]<>10),JMP LBL[995]"],
    "IF (F[n] AND R[n]<>N),JMP LBL[n]": [ 4, "IF (F[2:OFF:ToteOrig-Convs] AND R[386:Skip Pre-ConvPk]<>0),JMP LBL[231]"],
    "IF (PR[n,n]<N) THEN": [ 4, "IF (PR[91,3:*temp1]<50) THEN"],
    "IF (R[n]<(-N)),JMP LBL[n]": [ 4, "IF (R[94:*temp4]<(-90)),JMP LBL[330]"],
    "IF (R[n]<>N) THEN": [ 4, "IF (R[42:*CamDn-WaitTm]<>0) THEN"],
    "IF (R[n]<N) THEN": [ 4, "IF (R[71:*Cal-X pos]<650) THEN"],
    "IF (R[n]=N AND DO[n]),JMP LBL[n]": [ 4, "IF (R[10:*PK-Tool ID]=1 AND DO[203:At VacTL Nest Appr]),JMP LBL[300]"],
    "IF (R[n]=N AND R[n]=N),R[n]=(N)": [ 4, "IF (R[25:Active Zone]=1 AND R[26:Active Pallet]=1),R[20:Hood Label]=(24)"],
    "IF (R[n]>=(-N) AND R[n]<=(-N)),JMP LBL[n]": [ 4, "IF (R[86:*R angle-Save]>=(-190) AND R[86:*R angle-Save]<=(-170)),JMP LBL[111]"],
    "IF (R[n]>=N),JMP LBL[n]": [ 4, "IF (R[11:Tst-SlotInRack]>=26),JMP LBL[620]"],
    "IF DO[n]=OFF,CALL PROG": [ 4, "IF DO[35:At Safe]=OFF,CALL _SAFE"],
    "IF R[n]<N,JMP LBL[n]": [ 4, "IF R[83:*Z pos-Save]<50,JMP LBL[703]"],
    "IF R[n]>R[n],JMP LBL[n]": [ 4, "IF R[87:*Box/Pal Lg-save]>R[88:*Box/Pal Wd-Save],JMP LBL[706]"],
    "J P[n] N% CNTN": [ 4, "J P[2] 100% CNT100"],
    "J PR[n] R[n]% CNT R[n]": [ 4, "J PR[6:*Transit] R[215:Transit Spd]% CNT R[216:Transit CNT]"],
    "J PR[n] R[n]% CNTN Offset DB Nmm,DO[n]=OFF": [ 4, "J PR[43:Stack PK] R[31:Speed-J]% CNT100 Offset DB    5.0mm,DO[42:OFF:At Stack]=OFF"],
    "J PR[n] R[n]% FINE Tool_Offset": [ 4, "J PR[20:Zone1P1-Orig] R[31:Speed-J]% FINE Tool_Offset"],
    "L PR[n] R[n]mm/sec CNTN Wjnt": [ 4, "L PR[52:TrashApprTrns] R[203:BoxSpd-L]mm/sec CNT100 Wjnt"],
    "L PR[n] R[n]mm/sec FINE Tool_Offset Skip,LBL[n],PR[n]=LPOS": [ 4, "L PR[50:*Pallet Meas] R[207:*ScanSpd]mm/sec FINE Tool_Offset Skip,LBL[217],PR[49:*EdgeFind-LPOS]=LPOS"],
    "L PR[R[n]] Nmm/sec FINE": [ 4, "L PR[R[20]] 750mm/sec FINE"],
    "L PR[R[n]] R[n]mm/sec FINE Tool_Offset": [ 4, "L PR[R[20]] R[32:BoxSpd-L]mm/sec FINE Tool_Offset"],
    "R[n]=((R[n]+R[n])+R[n])": [ 4, "R[97:*temp]=((R[53:*Meas-HtOffs]+R[421:Lsr2UTL Dist])+R[443:Find-Z Tolr])"],
    "R[n]=N+R[n]": [ 4, "R[99:temp]=200+R[43:Pallet PK Z]"],
    "SKIP CONDITION DI[n]=ON": [ 4, "SKIP CONDITION DI[76:Box Outfd Pres]=ON"],
    "SKIP CONDITION GI[n]<=R[n]": [ 4, "SKIP CONDITION GI[6:Vac/PalMeas-1]<=R[97:*temp]"],
    "SR[n]=AR[n]": [ 4, "SR[1]=AR[2]"],
    "SR[n]=AR[n]+AR[n]": [ 4, "SR[1]=AR[2]+AR[3]"],
    "SR[n]=AR[n]+AR[n]+AR[n]": [ 4, "SR[1]=AR[2]+AR[3]+AR[4]"],
    "WAIT (GI[n]=N)": [ 4, "WAIT (GI[9:MeasAvg-1]=0)"],
    "WAIT (GI[n]>N)": [ 4, "WAIT (GI[9:MeasAvg-1]>0)"],
    "CALL PROG(AR[n])": [ 3, "CALL DSPWEBPG(AR[1])"],
    "F[n]=(DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n])": [ 3, "F[220:At Nrml RefPos]=(DO[203:At VacTL Nest Appr] OR DO[204:At PalTL Nest Appr] OR DO[205:At Scan-J4L] OR DO[206:At Scan-J4R] OR DO[207:At R-Cal Appr] OR DO[208:At L-Cal Appr] OR DO[209:At ScanAppr-L] OR DO[210:At ScanAppr-R])"],
    "F[n]=(R[n]<>N AND R[n]<>N)": [ 3, "F[503:DCS-At Reject]=(R[283:DCS-RjctZn-Sts]<>0 AND R[283:DCS-RjctZn-Sts]<>6)"],
    "F[n]=(R[n]>R[n] AND R[n]<R[n])": [ 3, "F[79:OFF:UT-X In Zone]=(R[85:LPOS X]>R[88] AND R[85:LPOS X]<R[89])"],
    "IF ((R[n]=N AND R[n]=N) AND !DO[n] AND !DO[n] AND !DO[n] AND !DO[n]),JMP LBL[n]": [ 3, "IF ((R[5]=0 AND R[100:JMP to LBL]=0) AND !DO[65:Vac-1 On] AND !DO[66:Blow-1 On] AND !DO[67:Vac-2 On] AND !DO[68:Blow-2 On]),JMP LBL[150]"],
    "IF ((R[n]=N OR R[n]=N) AND (DO[n] OR DO[n])),JMP LBL[n]": [ 3, "IF ((R[101:EOAT-Part Sts]=25 OR R[101:EOAT-Part Sts]=65) AND (DO[205:At Scan-J4L] OR DO[206:At Scan-J4R])),JMP LBL[230]"],
    "IF (ABS[R[n]]<N) THEN": [ 3, "IF (ABS[R[17]]<0) THEN"],
    "IF (ABS[R[n]]>N) THEN": [ 3, "IF (ABS[R[17]]>0) THEN"],
    "IF (DI[n]=OFF),JMP LBL[n]": [ 3, "IF (DI[3:OFF:Pause]=OFF),JMP LBL[198]"],
    "IF (DO[n] AND DO[n] AND DI[n] AND DI[n]),JMP LBL[n]": [ 3, "IF (DO[65:Vac-1 On] AND DO[68:Blow-2 On] AND DI[65:Vac-1 Ok] AND DI[68:Vac-4 Ok]),JMP LBL[200]"],
    "IF (F[n] OR R[n]<>N),JMP LBL[n]": [ 3, "IF (F[1:Part On Grip] OR R[101:*EOAT-Box Sts]<>0),JMP LBL[999]"],
    "IF (PR[n,n]>=N),JMP LBL[n]": [ 3, "IF (PR[91,3:*temp1]>=0),JMP LBL[290]"],
    "IF (PR[R[n],N]<PR[R[n],N]) THEN": [ 3, "IF (PR[R[80],1]<PR[R[81],1]) THEN"],
    "IF (R[n]<N AND R[n]>(-N)),JMP LBL[n]": [ 3, "IF (R[86:*R angle-Save]<0 AND R[86:*R angle-Save]>(-135)),JMP LBL[362]"],
    "IF (R[n]=N OR R[n]=N OR R[n]=N OR R[n]=N OR R[n]=N OR R[n]=N OR R[n]=N OR R[n]=N OR R[n]=N),JMP LBL[n]": [ 3, "IF (R[100:JMP to LBL]=10 OR R[100:JMP to LBL]=11 OR R[100:JMP to LBL]=20 OR R[100:JMP to LBL]=25 OR R[100:JMP to LBL]=30 OR R[100:JMP to LBL]=35 OR R[100:JMP to LBL]=40 OR R[100:JMP to LBL]=50 OR R[100:JMP to LBL]=55), JMP LBL[350]"],
    "IF (R[n]>N AND R[n]<N),JMP LBL[n]": [ 3, "IF (R[86:*R angle-Save]>0 AND R[86:*R angle-Save]<135),JMP LBL[262]"],
    "J P[n] N% FINE": [ 3, "J P[1] 100% FINE"],
    "J PR[R[n]] R[n]% CNTN Offset": [ 3, "J PR[R[20]] R[31:Speed-J]% CNT100 Offset"],
    "L P[n] Nmm/sec CNTN RT_LDN": [ 3, "L P[6:Pk Depar] 1000mm/sec CNT100 RT_LD50"],
    "L PR[n] max_speed CNTN": [ 3, "L PR[51:TrashAppr] max_speed CNT100"],
    "L PR[n] Nmm/sec FINE Skip,LBL[n],PR[n]=LPOS": [ 3, "L PR[41:Stack-Meas-Orig] 500mm/sec FINE Skip,LBL[710],PR[42:Pal Z LPOS]=LPOS"],
    "L PR[n] Nmm/sec FINE Tool_Offset DB Nmm,CALL PROG": [ 3, "L PR[20:Conv Pk] 300mm/sec FINE Tool_Offset DB   50.0mm,CALL _GRIP_CLAMP_PRE"],
    "L PR[R[n]] Nmm/sec FINE Tool_Offset": [ 3, "L PR[R[20]] 1500mm/sec FINE Tool_Offset"],
    "macro_N('s')": [ 3, "macro_115('NotAtPerch')"],
    "PR[n,n]=(PR[n,n]+R[n])": [ 3, "PR[42,3:*BoxSnsrPos]=(PR[40,3:*Box PL]+R[381:Snsr2Conv-Dist])"],
    "PR[n,n]=PR[R[n],N]+R[n]": [ 3, "PR[20,3:*Rack PKPL]=PR[R[27],3]+R[23:*Z-Offs]"],
    "R[n]=($sysvar$sysvar)": [ 3, "R[283:DCS-RjctZn-Sts]=($DCSS_PSTAT.$STATUS_CPC[13])"],
    "R[n]=(PR[n,n])": [ 3, "R[85:LPOS X]=(PR[98,1:LPOS])"],
    "R[n]=R[n]-N": [ 3, "R[94:*temp]=R[383:Scan2Conv-Dist]-40"],
    "WAIT (!DI[n] OR DI[n])": [ 3, "WAIT (!DI[23:Pal Outfd PL Rdy] OR DI[24:Pal Outfd Empty])"],
    "WAIT R[n]": [ 3, "WAIT R[475]"],
    "$sysvar=AR[n]": [ 2, "$WAITTMOUT=AR[1]"],
    "$sysvar$sysvar=(N)": [ 2, "$SSR.$STEPSTMTTYP=(1)"],
    "CALL PROG((-N),(-N),(-N),N)": [ 2, "CALL _SET_OFFS((-600),(-50),(-8),61)"],
    "CALL PROG((-N),N,R[n],N)": [ 2, "CALL _SET_OFFS((-75),0,R[64:*Pal PL-Z Press],61)"],
    "CALL PROG(R[n],N,N,N)": [ 2, "CALL _SET_OFFS(R[71:*Rjct PL Offs],0,40,61)"],
    "F[n]=(!DI[n] AND R[n]=N)": [ 2, "F[2:VacTL On]=(!DI[72:TL Chg Unlocked] AND R[5:Tool ID]=1)"],
    "F[n]=(DI[n] OR DI[n] OR DI[n] OR DI[n] OR DI[n] OR DI[n] OR DI[n] OR DI[n] OR DI[n])": [ 2, "F[1:Part On Grip]=(DI[32:EOAT Clamped] OR DI[65:Vac-1 Ok] OR DI[66:Vac-2 Ok] OR DI[67:Vac-3 Ok] OR DI[68:Vac-4 Ok] OR DI[69:Vac-5 Ok] OR DI[70:Vac-6 Ok] OR DI[71:Vac-7 Ok] OR DI[72:Vac-8 Ok])"],
    "F[n]=(DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n])": [ 2, "F[5:At RefPos]=(DO[33:At Home] OR DO[34:At TL Maint] OR DO[35:At Safe] OR DO[36:At Zero] OR DO[37:At Transit] OR DO[201:At Conv Appr] OR DO[202:At Conv Wait] OR DO[203:At Hopper Appr] OR DO[205:At Inspect Appr] OR DO[206:At Inspect Pos] OR DO[207:At Trash Appr])"],
    "F[n]=(DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n])": [ 2, "F[223:At L-Ln Pk Rtrt]=(DO[251:At L-Rtrt-MedZ/R180] OR DO[252:At L-Rtrt-MedZ/R90] OR DO[253:At L-Rtrt-MedZ/R-90] OR DO[254:At L-Rtrt-LrgZ/R180] OR DO[255:At L-Rtrt-LrgZ/R90] OR DO[256:At L-Rtrt-LrgZ/R-90])"],
    "F[n]=(DO[n] OR DO[n] OR DO[n] OR DO[n])": [ 2, "F[6:At BoxCnv RefPos]=(DO[261:At CnvApr-MedZ-J4L] OR DO[262:At CnvApr-MedZ-J4R] OR DO[263:At CnvApr-LrgZ-J4L] OR DO[264:At CnvApr-LrgZ-J4R])"],
    "GO[n]=(GI[n]+N)": [ 2, "GO[2:ClampPos-cmd]=(GI[2:ClampPos-act]+10)"],
    "IF (!DI[n] AND !DI[n]),JMP LBL[n]": [ 2, "IF (!DI[65:OFF:Clamp Ext-Up] AND !DI[68:ON :Hook Ret-Open]),JMP LBL[703]"],
    "IF (!F[n] AND !F[n] AND !F[n] AND !F[n] AND !F[n] AND !F[n]),JMP LBL[n]": [ 2, "IF (!F[85:OFF:In Z1P1 Zone] AND !F[86:OFF:In Z1P2 Zone] AND !F[87:OFF:In Z2P1 Zone] AND !F[88:OFF:In Z2P2 Zone] AND !F[89:OFF:In Stack Zone] AND !F[90:OFF:In Center Zone]),JMP LBL[700]"],
    "IF (!F[n] AND F[n]),JMP LBL[n]": [ 2, "IF (!F[1:Part on Grip] AND F[107:Pk Fail]),JMP LBL[200]"],
    "IF (!F[n] OR R[n]<>N),JMP LBL[n]": [ 2, "IF (!F[1:Part On Grip] OR R[101:*EOAT-Box Sts]<>40),JMP LBL[999]"],
    "IF (AR[n]=N) THEN": [ 2, "IF (AR[1]=0) THEN"],
    "IF (DI[n] AND R[n]<>N),JMP LBL[n]": [ 2, "IF (DI[28:OFF:Reject PL Cmd] AND R[385:Skip Scan-RjctPL]<>0),JMP LBL[212]"],
    "IF (DI[n]) THEN": [ 2, "IF (DI[24:Pal Outfd Empty]) THEN"],
    "IF (DO[n] Alarm]) THEN": [ 2, "IF (DO[49:SR[1] Alarm]) THEN"],
    "IF (F[n] AND !F[n]),JMP LBL[n]": [ 2, "IF (F[221:At L-Ln Pk Appr] AND !F[106:Appr Err]),JMP LBL[200]"],
    "IF (F[n] AND R[n]=N),JMP LBL[n]": [ 2, "IF (F[1:Part on Grip] AND R[101:EOAT-Part Sts]=10),JMP LBL[230]"],
    "IF (GI[n]<N) THEN": [ 2, "IF (GI[2:65456:EOAT Left Sens Lg]<400) THEN"],
    "IF (GI[n]>R[n]),R[n]=(GI[n])": [ 2, "IF (GI[12]>R[99:*temp]),R[99:*temp]=(GI[12])"],
    "IF (PR[n,n]<(-N) OR PR[n,n]>N),JMP LBL[n]": [ 2, "IF (PR[100,1:Rec JPOS]<(-20) OR PR[100,1:Rec JPOS]>20),JMP LBL[920]"],
    "IF (PR[n,n]<(-N)),JMP LBL[n]": [ 2, "IF (PR[99,2:*LPOS]<(-15)),JMP LBL[371]"],
    "IF (PR[n,n]>(-N)) THEN": [ 2, "IF (PR[99,1:*LPOS]>(-500)) THEN"],
    "IF (PR[n,n]>(PR[n,n]+N)),JMP LBL[n]": [ 2, "IF (PR[99,3:*LPOS]>(PR[70,3:Reject PL]+3)),JMP LBL[410]"],
    "IF (PR[n,n]>R[n]),JMP LBL[n]": [ 2, "IF (PR[91,3:*temp1]>R[96:*temp6]),JMP LBL[215]"],
    "IF (R[n]<(-N) OR R[n]>=N),JMP LBL[n]": [ 2, "IF (R[94:*temp4]<(-140) OR R[94:*temp4]>=170),JMP LBL[340]"],
    "IF (R[n]<=(-N)),R[n]=(R[n]+N)": [ 2, "IF (R[86:*R angle-Save]<=(-45)),R[86:*R angle-Save]=(R[86:*R angle-Save]+180)"],
    "IF (R[n]<>N AND R[n]<>N),R[n]=(N)": [ 2, "IF (R[33:*PreAppr-Zorient]<>1 AND R[33:*PreAppr-Zorient]<>2),R[33:*PreAppr-Zorient]=(1)"],
    "IF (R[n]<N AND R[n]>N),JMP LBL[n]": [ 2, "IF (R[94:*temp4]<170 AND R[94:*temp4]>10),JMP LBL[370]"],
    "IF (R[n]=N AND R[n]<>N),JMP LBL[n]": [ 2, "IF (R[100:*Tote-Sts ID]=10 AND R[383:Skip Scan-ConvPk]<>0),JMP LBL[210]"],
    "IF (R[n]=N AND R[n]=N AND DI[n]),JMP LBL[n]": [ 2, "IF (R[10:*PK-Tool ID]=1 AND R[5:Tool ID]=1 AND DI[71:TL Chg Locked]),JMP LBL[900]"],
    "IF (R[n]=N AND R[n]=N),JMP LBL[n]": [ 2, "IF (R[480:R-Lane Num]=1 AND R[490:L-Lane Num]=1),JMP LBL[700]"],
    "IF (R[n]=N AND R[n]>=N) THEN": [ 2, "IF (R[101:EOAT-Part Sts]=15 AND R[32:*Pre-Zoffs Found]>=50) THEN"],
    "IF (R[n]=N OR R[n]=N) THEN": [ 2, "IF (R[36:*ScanDn-Orient]=1 OR R[36:*ScanDn-Orient]=2) THEN"],
    "IF (R[n]=N OR R[n]=N),R[n]=(N)": [ 2, "IF (R[11:Tst-SlotInRack]=6 OR R[11:Tst-SlotInRack]=7),R[11:Tst-SlotInRack]=(8)"],
    "IF (R[n]=R[n]),JMP LBL[n]": [ 2, "IF (R[70:*Cal Lane]=R[480:R-Lane Num]),JMP LBL[120]"],
    "IF (R[n]>=(-N) AND R[n]<=N),JMP LBL[n]": [ 2, "IF (R[86:*R angle-Save]>=(-10) AND R[86:*R angle-Save]<=10),JMP LBL[111]"],
    "IF (R[n]>=(R[n]-N)),JMP LBL[n]": [ 2, "IF (R[63:*PalOut-Stk Ht]>=(R[431:Max Stack Ht]-25)),JMP LBL[411]"],
    "IF (R[n]>=N AND R[n]<N),JMP LBL[n]": [ 2, "IF (R[11:Tst-SlotInRack]>=15 AND R[11:Tst-SlotInRack]<26),JMP LBL[610]"],
    "IF (R[n]>=N AND R[n]>=N),DO[n]=(ON)": [ 2, "IF (R[81:*BoxLg-save]>=330 AND R[82:*BoxWd-save]>=290),DO[77:Vac-7 On]=(ON)"],
    "IF (R[n]>=N),R[n]=(R[n]-N)": [ 2, "IF (R[86:*R angle-Save]>=136),R[86:*R angle-Save]=(R[86:*R angle-Save]-180)"],
    "IF (R[n]>=R[n]),JMP LBL[n]": [ 2, "IF (R[63:*PalOut-Stk Ht]>=R[431:Max Stack Ht]),JMP LBL[140]"],
    "IF R[n]<>R[n],JMP LBL[n]": [ 2, "IF R[70:*Cal Lane]<>R[490:L-Lane Num],JMP LBL[700]"],
    "IF R[n]<R[n],JMP LBL[n]": [ 2, "IF R[87:*Box/Pal Lg-save]<R[88:*Box/Pal Wd-Save],JMP LBL[706]"],
    "L P[n] Nmm/sec FINE AP_LDN": [ 2, "L P[5:Pk] 1200mm/sec FINE AP_LD100"],
    "L PR[n] Nmm/sec CNTN DB Nmm,DO[n]=OFF": [ 2, "L PR[21:Conv Appr] 500mm/sec CNT100 DB    5.0mm,DO[38:At Conv]=OFF"],
    "L PR[n] Nmm/sec CNTN Offset Skip,LBL[n]": [ 2, "L PR[20:*Box Pk] 300mm/sec CNT50 Offset Skip,LBL[302]"],
    "L PR[n] Nmm/sec CNTN Skip,LBL[n]": [ 2, "L PR[42:*BoxSnsrPos] 100mm/sec CNT100 Skip,LBL[217]"],
    "L PR[n] Nmm/sec FINE Offset DB Nmm,CALL PROG AP_LDN": [ 2, "L PR[40:*Box PL] 750mm/sec FINE Offset DB   25.0mm,CALL _VAC_PL AP_LD30"],
    "L PR[n] R[n]mm/sec FINE Wjnt": [ 2, "L PR[35:*Dump-End] R[201:Speed-L]mm/sec FINE Wjnt"],
    "L PR[R[n]] R[n]mm/sec CNTN": [ 2, "L PR[R[20]] R[30:Speed-L]mm/sec CNT50"],
    "L PR[R[n]] R[n]mm/sec FINE": [ 2, "L PR[R[20]] R[32:BoxSpd-L]mm/sec FINE"],
    "macro_N('s',N)": [ 2, "macro_114('IsItSafe',21)"],
    "MESSAGE[P-coord error]": [ 2, "MESSAGE[P-coord error]"],
    "MESSAGE[R-coord error]": [ 2, "MESSAGE[R-coord error]"],
    "MESSAGE[W-coord error]": [ 2, "MESSAGE[W-coord error]"],
    "MESSAGE[X-coord error]": [ 2, "MESSAGE[X-coord error]"],
    "MESSAGE[Y-coord error]": [ 2, "MESSAGE[Y-coord error]"],
    "MESSAGE[Z-coord error]": [ 2, "MESSAGE[Z-coord error]"],
    "PR[n,n]=((PR[n,n]+R[n])+R[n])": [ 2, "PR[56,3:*PLpos-Meas]=((PR[56,3:*PLpos-Meas]+R[54:*Actv-Meas])+R[56:*UTL2Botm-Offs])"],
    "PR[n,n]=(PR[n,n]+R[n]-R[n])": [ 2, "PR[51,3:*PkPos-Meas]=(PR[50,3:*Pallet Meas]+R[54:*Actv-Meas]-R[55:*Top2Pk-Zoffs])"],
    "R[n]=((PR[n,n]-PR[n,n])+R[n])": [ 2, "R[43:*BoxPL-Z Offs]=((PR[45,3:*Snsr LPOS]-PR[42,3:*BoxSnsrPos])+R[42:*DropDist-Offs])"],
    "R[n]=((R[n]-N)*N)": [ 2, "R[91:*tempX]=((R[20:*RackNum]-1)*28)"],
    "R[n]=((R[n]-R[n])*(-N))": [ 2, "R[71:*Rjct PL Offs]=((R[81:*BoxLg-save]-R[280:Gripper Lg])*(-1))"],
    "R[n]=(PR[n,n]-(PR[n,n]-R[n]))": [ 2, "R[56:*UTL2Botm-Offs]=(PR[51,3:*PkPos-Meas]-(PR[50,3:*Pallet Meas]-R[83:*Z pos-Save]))"],
    "R[n]=PR[n,n]-PR[n,n]": [ 2, "R[383:Scan2Conv-Dist]=PR[111,3:Orig-Scan-L]-PR[46,3:Orig-BoxPL-L]"],
    "SKIP CONDITION DI[n]=ON OR DI[n]=ON": [ 2, "SKIP CONDITION DI[65:Vac-1 OK]=ON OR DI[67:Vac-2 OK]=ON"],
    "WAIT (!DI[n] AND DI[n])": [ 2, "WAIT (!DI[25:Box PL Rdy] AND DI[28:Box PL Ack])"],
    "WAIT (DO[n] OR DO[n] OR DO[n] OR DO[n])": [ 2, "WAIT (DO[231:At Lapr-SmX/MdZ/R180] OR DO[232:At Lapr-LgX/MdZ/R180] OR DO[233:At Lapr-SmX/MdZ/R90] OR DO[234:At Lapr-LgX/MdZ/R-90])"],
    "WAIT (DO[n] OR DO[n] OR DO[n])": [ 2, "WAIT (DO[221:At Rapr-SmX/MdZ/R0] OR DO[222:At Rapr-LgX/MdZ/R0] OR DO[224:At Rapr-LgX/MdZ/R-90])"],
    "$sysvar$sysvar=R[n]": [ 1, "$SSR.$STEPSTMTTYP=R[348]"],
    "ABORT": [ 1, "ABORT"],
    "CALL PROG((-N),(-N),N,N)": [ 1, "CALL _SET_OFFS((-2),(-2),30,60)"],
    "CALL PROG(AR[n],AR[n],AR[n],AR[n],AR[n],AR[n],AR[n],AR[n],AR[n],AR[n])": [ 1, "CALL GESNDDAT(AR[1],AR[2],AR[3],AR[4],AR[5],AR[6],AR[7],AR[8],AR[9],AR[10])"],
    "CALL PROG(AR[n],AR[n],AR[n],AR[n],AR[n],AR[n])": [ 1, "CALL GESNDSYS(AR[1],AR[2],AR[3],AR[4],AR[5],AR[6])"],
    "CALL PROG(AR[n],AR[n],AR[n])": [ 1, "CALL GESNDEVT(AR[1],AR[2],AR[3])"],
    "CALL PROG(AR[n],N,AR[n],AR[n],AR[n],AR[n],AR[n],AR[n],AR[n],AR[n])": [ 1, "CALL GESNDDAT(AR[1],1,AR[2],AR[3],AR[4],AR[5],AR[6],AR[7],AR[8],AR[9])"],
    "CALL PROG(AR[n],N,AR[n])": [ 1, "CALL GESNDEVT(AR[1],1,AR[2])"],
    "DO[n]=(DO[n])": [ 1, "DO[44:OFF:At Scanner]=(DO[203:OFF:At Scan Pos])"],
    "ELSE,CALL PROG": [ 1, "ELSE,CALL ABORTIT"],
    "F[n]=(!DI[n] OR !DI[n])": [ 1, "F[1:ON :Part in Grip]=(!DI[65:OFF:Clamp Ext-Up] OR !DI[68:ON :Hook Ret-Open])"],
    "F[n]=(!DI[n] OR (GI[n]<N AND !DI[n]))": [ 1, "F[1:Part on Grip]=(!DI[69:Clamp Full Open ] OR (GI[5:Pal Clamp Wd]<1350 AND !DI[70:Clamp Full Cls]))"],
    "F[n]=(ABS[R[n]]<=N)": [ 1, "F[15:ON :Hood Aligned]=(ABS[R[17]]<=7)"],
    "F[n]=(DI[n] AND R[n]=N)": [ 1, "F[4:No TL On]=(DI[72:TL Chg Unlocked] AND R[5:Tool ID]=0)"],
    "F[n]=(DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n])": [ 1, "F[5:ON :At RefPos]=(DO[33:OFF:At Home] OR DO[34:OFF:At TL Maint] OR DO[35:OFF:At Safe] OR DO[36:OFF:At Zero] OR DO[37:OFF:At Transit] OR DO[201:OFF:At Conv1/3 Appr] OR DO[202:OFF:At Recon Appr] OR DO[203:OFF:At Scan Pos] OR DO[204:OFF:At Inspct Pos] OR DO[205:OFF:At Hopper Appr] OR DO[206:OFF:At Dump Pos] OR DO[207:OFF:At Dump-Divide Pos] OR DO[208:OFF:At Reject Appr] OR DO[211:ON :At L-RacksApr] OR DO[212:OFF:At R-RacksApr])"],
    "F[n]=(DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n])": [ 1, "F[5:OFF:At RefPos]=(DO[33:OFF:At Home] OR DO[34:OFF:At Tool Maint] OR DO[35:OFF:At Safe] OR DO[36:OFF:At Zero] OR DO[37:OFF:At Transit] OR DO[43:OFF:At Zone1 Appr] OR DO[44:OFF:At Zone2 Appr])"],
    "F[n]=(DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR F[n] OR F[n] OR F[n] OR F[n] OR F[n] OR F[n] OR F[n])": [ 1, "F[5:At Ref Pos]=(DO[33:At Home] OR DO[34:At TL Maint] OR DO[35:At Safe] OR DO[36:At Zero] OR DO[37:At Transit] OR F[6:At BoxCnv RefPos] OR F[7:At PalCnv RefPos] OR F[220:At Nrml RefPos] OR F[221:At L-Ln Pk Appr] OR F[222:At R-Ln Pk Appr] OR F[223:At L-Ln Pk Rtrt] OR F[224:At R-Ln Pk Rtrt])"],
    "F[n]=(DO[n] OR DO[n] OR DO[n])": [ 1, "F[1:OFF:Part On Grip]=(DO[32:OFF:EOAT Grab Pallet] OR DO[30:OFF:EOAT Clamp] OR DO[29:OFF:EOAT Clamp Center])"],
    "F[n]=(R[n]=N OR R[n]=N)": [ 1, "F[2:OFF:ToteOrig-Convs]=(R[5:*Grp-ToteID]=200 OR R[5:*Grp-ToteID]=201)"],
    "F[n]=(R[n]>=N AND R[n]<=N)": [ 1, "F[3:OFF:ToteOrig-Racks]=(R[5:*Grp-ToteID]>=1 AND R[5:*Grp-ToteID]<=168)"],
    "F[n]=(R[n]>N)": [ 1, "F[7:OFF:Mult Tasks Rdy]=(R[370:*Num Tasks Rdy]>1)"],
    "F[R[n]]=(F[n] AND F[n] AND F[n])": [ 1, "F[R[82]]=(F[79:OFF:UT-X In Zone] AND F[80:OFF:UT-Y In Zone] AND F[81:OFF:UT-Z In Zone])"],
    "IF (!F[n] AND !DI[n]) THEN": [ 1, "IF (!F[300:TL Chg Enbl] AND !DI[72:TL Chg Unlocked]) THEN"],
    "IF ((!DI[n] AND !DI[n]) AND DI[n]),JMP LBL[n]": [ 1, "IF ((!DI[17:OFF:Infd Pk Rdy] AND !DI[18:OFF:Recon Pk Rdy]) AND DI[21:OFF:RackPK Rdy]),JMP LBL[120]"],
    "IF ((!DO[n] AND !DO[n]) AND (DO[n] OR DO[n])) THEN": [ 1, "IF ((!DO[206:OFF:At Dump Pos] AND !DO[207:OFF:At Dump-Divide Pos]) AND (DO[23:OFF:Tote in Pos] OR DO[24:OFF:Dump Dn Ack])) THEN"],
    "IF ((DI[n] OR DI[n]) AND !DI[n]),JMP LBL[n]": [ 1, "IF ((DI[17:OFF:Infd Pk Rdy] OR DI[18:OFF:Recon Pk Rdy]) AND !DI[21:OFF:RackPK Rdy]),JMP LBL[110]"],
    "IF ((DI[n] OR DI[n]) AND DI[n]),JMP LBL[n]": [ 1, "IF ((DI[17:OFF:Infd Pk Rdy] OR DI[18:OFF:Recon Pk Rdy]) AND DI[21:OFF:RackPK Rdy]),JMP LBL[130]"],
    "IF ((DI[n] OR DI[n])),JMP LBL[n]": [ 1, "IF ((DI[19:OFF:Outfd PL Rdy] OR DI[20:OFF:Recon PL Rdy])),JMP LBL[926]"],
    "IF ((R[n]<=N) AND (R[n]>(-N))),R[n]=(R[n]+N)": [ 1, "IF ((R[86:*R angle-Save]<=0) AND (R[86:*R angle-Save]>(-135))),R[86:*R angle-Save]=(R[86:*R angle-Save]+180)"],
    "IF ((R[n]<N) AND (R[n]>(-N))),R[n]=(R[n]+N)": [ 1, "IF ((R[86:*R angle-Save]<0) AND (R[86:*R angle-Save]>(-45))),R[86:*R angle-Save]=(R[86:*R angle-Save]+180)"],
    "IF ((R[n]=N) AND R[n]<>N),JMP LBL[n]": [ 1, "IF ((R[100:*Tote-Sts ID]=60) AND R[385:Skip Scan-RjctPL]<>0),JMP LBL[210]"],
    "IF ((R[n]>=N) AND (R[n]<N)),R[n]=(R[n]-N)": [ 1, "IF ((R[86:*R angle-Save]>=0) AND (R[86:*R angle-Save]<135)),R[86:*R angle-Save]=(R[86:*R angle-Save]-180)"],
    "IF ((R[n]>N) AND (R[n]<N)),R[n]=(R[n]-N)": [ 1, "IF ((R[86:*R angle-Save]>0) AND (R[86:*R angle-Save]<45)),R[86:*R angle-Save]=(R[86:*R angle-Save]-180)"],
    "IF (DO[n]) THEN": [ 1, "IF (DO[33:At Home]) THEN"],
    "IF (DO[n]=OFF),CALL PROG": [ 1, "IF (DO[35:OFF:At Safe]=OFF),CALL _SAFE"],
    "IF (F[n] AND (R[n]=N OR R[n]=N)),JMP LBL[n]": [ 1, "IF (F[1:Part on Grip] AND (R[101:EOAT-Part Sts]=20 OR R[101:EOAT-Part Sts]=25)),JMP LBL[240]"],
    "IF (F[n] AND F[n] AND F[n]) THEN": [ 1, "IF (F[1017:BGL-Custom ON] AND F[1018:BGL-TaskLog ON] AND F[1019:BGL-LnData ON]) THEN"],
    "IF (F[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n] OR DO[n]),JMP LBL[n]": [ 1, "IF (F[6:At BoxCnv RefPos] OR DO[33:At Home] OR DO[205:At Scan-J4L] OR DO[206:At Scan-J4R] OR DO[209:At ScanAppr-L] OR DO[210:At ScanAppr-R]),JMP LBL[155]"],
    "IF (F[n] OR DO[n] OR DO[n]),JMP LBL[n]": [ 1, "IF (F[6:At BoxCnv RefPos] OR DO[209:At ScanAppr-L] OR DO[210:At ScanAppr-R]),JMP LBL[210]"],
    "IF (GI[n]<(R[n]-N)),JMP LBL[n]": [ 1, "IF (GI[5:Pal Clamp Wd]<(R[476:AR-GrpClsWd]-80)),JMP LBL[702]"],
    "IF (R[n]<>N AND R[n]<>N AND R[n]<>N AND R[n]<>N),JMP LBL[n]": [ 1, "IF (R[100:*Tote-Sts ID]<>10 AND R[100:*Tote-Sts ID]<>11 AND R[100:*Tote-Sts ID]<>60 AND R[100:*Tote-Sts ID]<>61),JMP LBL[700]"],
    "IF (R[n]<N OR R[n]>N),R[n]=(N)": [ 1, "IF (R[6:*Payload ID]<1 OR R[6:*Payload ID]>2),R[6:*Payload ID]=(2)"],
    "IF (R[n]>R[n]) THEN": [ 1, "IF (R[32:*Pre-Zoffs Found]>R[94:*temp]) THEN"],
    "IF (R[R[n]]<=N),JMP LBL[n]": [ 1, "IF (R[R[199]]<=0),JMP LBL[700]"],
    "IF (R[R[n]]>N),JMP LBL[n]": [ 1, "IF (R[R[199]]>0),JMP LBL[700]"],
    "IF (RI[n]),JMP LBL[n]": [ 1, "IF (RI[1:Vac Made]),JMP LBL[620]"],
    "IF R[n]=N,CALL PROG": [ 1, "IF R[21:Hood Position]=0,CALL ABORTIT"],
    "IF R[n]>=N,JMP LBL[n]": [ 1, "IF R[75:*RdyWait-Timer]>=5,JMP LBL[270]"],
    "J P[n] N% CNTN DB Nmm,DO[n]=OFF": [ 1, "J P[6:Tansit PK] 75% CNT75 DB   10.0mm,DO[38:OFF:At Zone1P1]=OFF"],
    "J PR[n] R[n]% CNTN ACCN": [ 1, "J PR[91:*temp1] R[104:ToteSpd-J]% CNT100 ACC50"],
    "J PR[n] R[n]% FINE Offset": [ 1, "J PR[50:Trash PL] R[203:BoxSpd-L]% FINE Offset"],
    "L PR[n] max_speed CNTN Offset": [ 1, "L PR[22:ConvPk Wait] max_speed CNT100 Offset"],
    "L PR[n] Nmm/sec CNTN Skip,LBL[n] Offset": [ 1, "L PR[42:*BoxSnsrPos] 750mm/sec CNT100 Skip,LBL[216] Offset"],
    "L PR[n] Nmm/sec FINE Tool_Offset Skip,LBL[n]": [ 1, "L PR[99:temp] 100mm/sec FINE Tool_Offset Skip,LBL[700]"],
    "L PR[n] R[n]mm/sec CNTN Tool_Offset AP_LDN": [ 1, "L PR[30:*Conv PKPL] R[103:ToteSpd-L]mm/sec CNT100 Tool_Offset AP_LD100"],
    "macro_N": [ 1, "macro_119"],
    "MESSAGE[Cal:P-coord error]": [ 1, "MESSAGE[Cal:P-coord error]"],
    "MESSAGE[Cal:R-coord error]": [ 1, "MESSAGE[Cal:R-coord error]"],
    "MESSAGE[Cal:W-coord error]": [ 1, "MESSAGE[Cal:W-coord error]"],
    "MESSAGE[Cal:X-coord error]": [ 1, "MESSAGE[Cal:X-coord error]"],
    "MESSAGE[Cal:Y-coord error]": [ 1, "MESSAGE[Cal:Y-coord error]"],
    "MESSAGE[Cal:Z-coord error]": [ 1, "MESSAGE[Cal:Z-coord error]"],
    "PAYLOAD[R[n]]": [ 1, "PAYLOAD[R[6]]"],
    "PR[n,n]=PR[n,n]-R[n]": [ 1, "PR[55,1:*PalStk Meas]=PR[55,1:*PalStk Meas]-R[81:*X pos-Save]"],
    "R[n]=((PR[n,n]-PR[n,n]))": [ 1, "R[32:*Pre-Zoffs Found]=((PR[29,3:*PreHtFind-LPOS]-PR[42,3:*BoxSnsrPos]))"],
    "R[n]=((R[n]+R[n])/N)": [ 1, "R[405:V-Avg]=((R[406:V1]+R[407:V2])/2)"],
    "R[n]=(ATAN[R[n]])": [ 1, "R[15:Align Angle]=(ATAN[R[15]])"],
    "R[n]=(R[n]-R[n])": [ 1, "R[93:*temp-Z]=(R[32:*Pre-Zoffs Found]-R[94:*temp])"],
    "R[n]=$sysvar$sysvar": [ 1, "R[348]=$SSR.$STEPSTMTTYP"],
    "R[n]=GI[n]-GI[n]": [ 1, "R[17:Alignment Delta]=GI[3:218:EOAT Left Sens Sm]-GI[4:256:EOAT Left Sens 1]"],
    "R[n]=R[n]/(-N)": [ 1, "R[15:Align Angle]=R[17:Alignment Delta]/(-830)"],
    "R[n]=R[n]+R[n]+R[n]": [ 1, "R[21:*SlotNum]=R[91:*tempX]+R[92:*tempY]+R[26:*Slot-Row]"],
    "R[n]=R[n]+R[n]+R[n]+R[n]+R[n]": [ 1, "R[370:*Num Tasks Rdy]=R[371:*Outfd1 PL Rdy]+R[372:*ReconPL Rdy]+R[373:*RackPL Rdy]+R[374:*Hopper Rdy]+R[375:*RjctPL Rdy]"],
    "SKIP CONDITION GI[n]>=N AND GI[n]<=N": [ 1, "SKIP CONDITION GI[6:133:EOAT Inner Sens]>=125 AND GI[6:133:EOAT Inner Sens]<=150"],
    "WAIT (DI[n] AND !DI[n])": [ 1, "WAIT (DI[23:OFF:Hopper Rdy] AND !DI[24:OFF:Hopper Done])"],
    "WAIT (DO[n]) TIMEOUT,LBL[n]": [ 1, "WAIT (DO[43:OFF:At Reject]) TIMEOUT,LBL[731]"],
    "WAIT (GI[n]<N) TIMEOUT,LBL[n]": [ 1, "WAIT (GI[5:Pal Clamp Wd]<1330) TIMEOUT,LBL[701]"],
    "WAIT (GO[n]=R[n])": [ 1, "WAIT (GO[6:Vac Set Pt]=R[408:Set])"],
    "WHEN DO[n]=ON AND DI[n]=OFF,CALL ...": [ 1, "WHEN DO[65:Vac-1 ON]=ON AND DI[65:Vac-1 OK]=OFF,CALL ..."]
   }
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = dict;
  global.TP_SHAPES = dict;
})(typeof window !== 'undefined' ? window : globalThis);
