#!/usr/bin/env node
/* Regenerates js/samples.js from samples/*.LS so the demo cell works from file://
 * Run after editing anything in samples/:  node tools/build-samples.js
 */
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const samplesDir = path.join(root, 'samples');
const out = {};

for (const f of fs.readdirSync(samplesDir).sort()) {
  if (!/\.ls$/i.test(f)) continue;
  out[f.replace(/\.ls$/i, '').toUpperCase()] = fs.readFileSync(path.join(samplesDir, f), 'utf8');
}

const js = '/* Generated by tools/build-samples.js — do not edit by hand. */\n' +
  'window.FANUC_SAMPLES = ' + JSON.stringify(out, null, 1) + ';\n';

fs.writeFileSync(path.join(root, 'js', 'samples.js'), js);
console.log('Wrote js/samples.js with', Object.keys(out).length, 'programs:', Object.keys(out).join(', '));
