[*SYSTEM*]$CELL_FLOOR  Storage: SHADOW  Access: RW  : POSITION = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000

[*SYSTEM*]$CELL_GRP  Storage: SHADOW  Access: RW  : ARRAY[1] OF CELL_GRP_T
     Field: $CELL_GRP[1].$CELL_FRAME Access: RW: POSITION = 
  Group: 0   Config: 
  X:     0.000   Y:     0.000   Z:   450.000
  W:     0.000   P:     0.000   R:     0.000
     Field: $CELL_GRP[1].$MOUNT_LOC Access: RW: POSITION = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:   450.000
  W:     0.000   P:     0.000   R:     0.000
     Field: $CELL_GRP[1].$CF_METHOD Access: RW: INTEGER = 1
     Field: $CELL_GRP[1].$CPY_SRC_IDX Access: RW: INTEGER = Uninitialized
     Field: $CELL_GRP[1].$PLATFRM_OFS Access: RW: POSITION = Uninitialized
     Field: $CELL_GRP[1].$PLATFRM_DIM Access: RW: VECTOR = Uninitialized
     Field: $CELL_GRP[1].$BASE_OFFSET Access: RW: POSITION = Uninitialized
     Field: $CELL_GRP[1].$BASE_DIM Access: RW: VECTOR = Uninitialized
     Field: $CELL_GRP[1].$AUX_ORDER  ARRAY[3] OF INTEGER
      [1] = Uninitialized
      [2] = Uninitialized
      [3] = Uninitialized
     Field: $CELL_GRP[1].$AUX_XYZ_MAP  ARRAY[3] OF INTEGER
      [1] = Uninitialized
      [2] = Uninitialized
      [3] = Uninitialized
     Field: $CELL_GRP[1].$AUX_OFFSET  ARRAY[3] OF REAL
      [1] = Uninitialized
      [2] = Uninitialized
      [3] = Uninitialized
     Field: $CELL_GRP[1].$AUX_LENGTH  ARRAY[3] OF REAL
      [1] = Uninitialized
      [2] = Uninitialized
      [3] = Uninitialized
     Field: $CELL_GRP[1].$ATTCH_GP_MS Access: RW: INTEGER = Uninitialized
     Field: $CELL_GRP[1].$AUTORAIL Access: RW: INTEGER = Uninitialized

[*SYSTEM*]$MNUFRAME  Storage: SHADOW  Access: RW  : ARRAY[1,9] OF POSITION
    [1,1] = 
  Group: 1   Config: N D B, 0, 0, 0
  X: -1911.500   Y:  -761.998   Z:   982.602
  W:     -.472   P:     -.011   R:    88.994
    [1,2] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:  -288.339   Y: -2023.417   Z:   978.600
  W:      .277   P:      .530   R:   149.656
    [1,3] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:  1615.661   Y: -1274.408   Z:   982.600
  W:      .460   P:      .111   R:  -150.667
    [1,4] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:  1896.500   Y:   762.000   Z:   977.600
  W:     0.000   P:     0.000   R:   -90.000
    [1,5] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:   295.838   Y:  2036.407   Z:   982.600
  W:     0.000   P:     0.000   R:   -30.000
    [1,6] = 
  Group: 1   Config: N D B, 0, 0, 0
  X: -1615.661   Y:  1274.408   Z:   982.600
  W:     0.000   P:     0.000   R:    30.000
    [1,7] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000
    [1,8] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000
    [1,9] = 
  Group: 1   Config: F U T, 0, 0, 0
  X:  1593.968   Y:  -955.765   Z:   999.063
  W:  -166.487   P:    89.527   R:   -47.154

[*SYSTEM*]$MNUFRAMENUM  Storage: SHADOW  Access: RW  : ARRAY[1] OF BYTE
  [1] = 3

[*SYSTEM*]$MNUTOOL  Storage: SHADOW  Access: RW  : ARRAY[1,10] OF POSITION
    [1,1] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:  -275.000   Y:     0.000   Z:   280.000
  W:  -180.000   P:   -90.000   R:     0.000
    [1,2] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000
    [1,3] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000
    [1,4] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000
    [1,5] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000
    [1,6] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000
    [1,7] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000
    [1,8] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000
    [1,9] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000
    [1,10] = 
  Group: 1   Config: N D B, 0, 0, 0
  X:     0.000   Y:     0.000   Z:     0.000
  W:     0.000   P:     0.000   R:     0.000

[*SYSTEM*]$MNUTOOLNUM  Storage: SHADOW  Access: RW  : ARRAY[1] OF BYTE
  [1] = 1

